export const STEP_CATEGORIES = [
  { id: "add", name: "加法" },
  { id: "subtract", name: "减法" },
  { id: "multiply", name: "乘法" },
  { id: "divide", name: "除法" },
  { id: "mixed", name: "混合" },
  { id: "decimal", name: "小数" },
  { id: "fraction", name: "分数" },
];

export const STEPS = [
  {
    id: 4,
    category: "add",
    title: "第4步",
    name: "100以内加法",
    shortName: "加法100以内",
    description: "两个整数相加，结果不超过100。",
  },
  {
    id: 5,
    category: "subtract",
    title: "第5步",
    name: "20以内两位数减一位数",
    shortName: "20以内减法",
    description: "20以内，两位数减一位数，结果不为负数。",
  },
  {
    id: 6,
    category: "subtract",
    title: "第6步",
    name: "100以内两位数减一位数",
    shortName: "两位数减一位数",
    description: "100以内，两位数减一位数，结果不为负数。",
  },
  {
    id: 7,
    category: "subtract",
    title: "第7步",
    name: "100以内两位数减两位数",
    shortName: "两位数减两位数",
    description: "两位数减两位数，结果不为负数。",
  },
  {
    id: 8,
    category: "mixed",
    title: "第8步",
    name: "100以内加减混合",
    shortName: "100以内加减",
    description: "100以内加法和减法混合，结果不为负数。",
  },
  {
    id: 9,
    category: "mixed",
    title: "第9步",
    name: "1000以内加减法",
    shortName: "1000以内加减",
    description: "1000以内加法和减法混合，结果保持在0到1000之间。",
  },
  {
    id: 10,
    category: "multiply",
    title: "第10步",
    name: "九九乘法",
    shortName: "九九乘法",
    description: "1到9的乘法口诀。",
  },
  {
    id: 11,
    category: "multiply",
    title: "第11步",
    name: "两位数乘一位数",
    shortName: "两位数×一位数",
    description: "两位数乘一位数。",
  },
  {
    id: 12,
    category: "multiply",
    title: "第12步",
    name: "三位数乘一位数",
    shortName: "三位数×一位数",
    description: "三位数乘一位数。",
  },
  {
    id: 13,
    category: "multiply",
    title: "第13步",
    name: "四位数乘一位数",
    shortName: "四位数×一位数",
    description: "四位数乘一位数。",
  },
  {
    id: 14,
    category: "multiply",
    title: "第14步",
    name: "整十整百数乘法",
    shortName: "整十整百乘法",
    description: "整十数或整百数乘一位数。",
  },
  {
    id: 15,
    category: "multiply",
    title: "第15步",
    name: "两位数乘两位数",
    shortName: "两位数×两位数",
    description: "两位数乘两位数。",
  },
  {
    id: 16,
    category: "divide",
    title: "第16步",
    name: "九九范围内除法",
    shortName: "九九除法",
    description: "乘法口诀范围内的整除除法。",
  },
  {
    id: 17,
    category: "divide",
    title: "第17步",
    name: "两位数除以一位数，无余数",
    shortName: "两位数÷一位数",
    description: "两位数除以一位数，结果整除。",
  },
  {
    id: 18,
    category: "divide",
    title: "第18步",
    name: "两位数除以一位数，有余数",
    shortName: "有余数除法",
    description: "两位数除以一位数，需要填写商和余数。",
    answerType: "quotientRemainder",
  },
  {
    id: 19,
    category: "divide",
    title: "第19步",
    name: "三位数除以一位数",
    shortName: "三位数÷一位数",
    description: "三位数除以一位数，结果整除。",
  },
  {
    id: 20,
    category: "divide",
    title: "第20步",
    name: "四位数除以一位数",
    shortName: "四位数÷一位数",
    description: "四位数除以一位数，结果整除。",
  },
  {
    id: 21,
    category: "divide",
    title: "第21步",
    name: "多位数除以两位数",
    shortName: "多位数÷两位数",
    description: "三位数或四位数除以两位数，结果整除。",
  },
  {
    id: 22,
    category: "mixed",
    title: "第22步",
    name: "整数四则混合运算",
    shortName: "整数四则混合",
    description: "整数加、减、乘、除混合，包含两步运算。",
  },
  {
    id: 23,
    category: "decimal",
    title: "第23步",
    name: "小数加法",
    shortName: "小数加法",
    description: "一位小数或两位小数的加法。",
    answerType: "decimal",
  },
  {
    id: 24,
    category: "decimal",
    title: "第24步",
    name: "小数减法",
    shortName: "小数减法",
    description: "一位小数或两位小数的减法，结果不为负数。",
    answerType: "decimal",
  },
  {
    id: 25,
    category: "decimal",
    title: "第25步",
    name: "小数加减混合",
    shortName: "小数加减",
    description: "小数加法和减法混合练习。",
    answerType: "decimal",
  },
  {
    id: 26,
    category: "decimal",
    title: "第26步",
    name: "小数乘整数",
    shortName: "小数×整数",
    description: "一位小数或两位小数乘一位整数。",
    answerType: "decimal",
  },
  {
    id: 33,
    category: "fraction",
    title: "第33步",
    name: "同分母分数加减法",
    shortName: "同分母加减",
    description: "分母相同的分数加法和减法。",
    answerType: "fraction",
  },
  {
    id: 34,
    category: "fraction",
    title: "第34步",
    name: "异分母分数加减法",
    shortName: "异分母加减",
    description: "分母不同的分数加法和减法。",
    answerType: "fraction",
  },
  {
    id: 35,
    category: "fraction",
    title: "第35步",
    name: "带分数加减法",
    shortName: "带分数加减",
    description: "带分数和分数的加法、减法。",
    answerType: "fraction",
  },
  {
    id: 36,
    category: "fraction",
    title: "第36步",
    name: "分数乘整数",
    shortName: "分数×整数",
    description: "分数乘一位整数。",
    answerType: "fraction",
  },
  {
    id: 37,
    category: "fraction",
    title: "第37步",
    name: "分数乘分数",
    shortName: "分数×分数",
    description: "两个分数相乘。",
    answerType: "fraction",
  },
  {
    id: 38,
    category: "fraction",
    title: "第38步",
    name: "分数除以整数",
    shortName: "分数÷整数",
    description: "分数除以一位整数。",
    answerType: "fraction",
  },
  {
    id: 39,
    category: "fraction",
    title: "第39步",
    name: "分数除以分数",
    shortName: "分数÷分数",
    description: "两个分数相除。",
    answerType: "fraction",
  },
  {
    id: 40,
    category: "fraction",
    title: "第40步",
    name: "分数四则混合",
    shortName: "分数混合",
    description: "分数加、减、乘、除混合练习。",
    answerType: "fraction",
  },
];

export const STEP_IDS = STEPS.map((step) => step.id);

export function getStep(stepId) {
  return STEPS.find((step) => step.id === Number(stepId)) ?? STEPS[0];
}

export function getNextStepId(stepId) {
  const index = STEP_IDS.indexOf(Number(stepId));
  return index >= 0 && index < STEP_IDS.length - 1 ? STEP_IDS[index + 1] : null;
}

export function getCategoryName(categoryId) {
  return STEP_CATEGORIES.find((category) => category.id === categoryId)?.name ?? "其他";
}
